Fix AnyUrl not being encodable
BeanieODM/beanie pull request #1071
Opened 2024-11-23 08:08 UTC by 07pepa

On nevest pydantic  anyurl is not ecodable

2024-11-23 19:15 UTC, staticxterm commented
Looks good, please add some tests to tests/odm/test_encoder.py or elsewhere?
How come that the current test case "test_should_encode_pydantic_v2_url_correctly" didn't catch this?

2024-11-26 15:11 UTC, 07pepa commented
> Looks good, please add some tests to tests/odm/test_encoder.py or elsewhere? How come that the current test case "test_should_encode_pydantic_v2_url_correctly" didn't catch this?

there already is test that would fail without change ... hiden by using older version upgrading version uncovered this.

2024-11-28 21:00 UTC, staticxterm commented
> > Looks good, please add some tests to tests/odm/test_encoder.py or elsewhere? How come that the current test case "test_should_encode_pydantic_v2_url_correctly" didn't catch this?
> 
> there already is test that would fail without change ... hiden by using older version upgrading version uncovered this.

Okay, I get this, but I believe there should be a kind of a test that would catch this regression, if possible. But I see you've added the OpenAPI schema generation test. I guess this could suffice for now.
By the way, did this test fail under Pydantic v1 only, under Pydantic v2 only, under some specific Pydantic version or what was the case here?

2024-11-28 21:01 UTC, staticxterm requested changes

2024-11-30 13:19 UTC, Riverfount requested changes
Just review the notes of @staticxterm and the Github Action is failing, fix this issues.

2024-12-06 23:31 UTC, staticxterm commented
Looked into this a bit, it seems there's a lot of breakage with Url types in Pydantic v2.10.x. It was still broken for me on current latest 2.10.3. I suggest to reduce this PR to a minimum change in project.toml where we skip the Pydantic minor version range which is causing these issues (works fine on 2.9.2, started breaking with 2.10.x) and lock it down to a known working version (2.9.2) in our CI as well. Hopefully Pydantic team fixes it upstream with 2.11.0+ or some other patch version on 2.10.x (doesn't seem like it).

2025-02-05 02:35 UTC, closed without merging