Bulk Writer improving & bulk_writer method for document and possibility to bypass mongo document validation + comment parameter
BeanieODM/beanie pull request #1079
Opened 2024-12-06 11:28 UTC by CAPITAINMARVEL

- Reworked it
added:
- bypass_document_validation
- comment parameter
- method to use bulk_write on Document and UnionDoc model

handle
https://github.com/BeanieODM/beanie/discussions/327

2024-12-10 22:02 UTC, staticxterm requested changes
The BulkWriter changes look good, needs some more polishing...

2024-12-10 22:02 UTC, staticxterm commented on tests/odm/documents/test_bulk_write.py
> +async def test_bypass_document_validation(documents_not_inserted):
```suggestion
async def test_bypass_document_validation():
```
Same as previous comment, the `documents_not_inserted` fixture is not needed.
Test is passing even without it.

2024-12-10 22:02 UTC, staticxterm commented on tests/odm/documents/test_bulk_write.py
> +async def test_comment(documents_not_inserted):
```suggestion
async def test_comment():
```
Nothing is being inserted to the DB, so the `documents_not_inserted` fixture is not needed.
Test is passing even without it.

2024-12-11 22:44 UTC, staticxterm requested changes
Looks good, have one final nitpick about one test assertion and some typing improvements if you agree...

2024-12-11 22:44 UTC, staticxterm commented on beanie/odm/bulk.py
>      ):
```suggestion
    ) -> None:
```
In an effort to fully type annotate everything, mypy under strict mode requires "-> None" typing in such cases.

2024-12-11 22:44 UTC, staticxterm commented on beanie/odm/bulk.py
>      async def __aenter__(self):
```suggestion
    async def __aenter__(self) -> "BulkWriter":
```

2024-12-11 22:44 UTC, staticxterm commented on beanie/odm/bulk.py
>      async def __aexit__(self, exc_type, exc, tb):
```suggestion
    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> None:
```
```python
from types import TracebackType
```

2024-12-12 21:16 UTC, staticxterm approved these changes
Looks great, thank you!

2024-12-13 01:23 UTC, adeelsohailahmed approved these changes
Good stuff! Please update the PR's title to be a bit more descriptive for the change log.

2024-12-22 21:51 UTC, roman-right requested changes
Please take a look at the few comments I left.
In general, it is a great job! Thank you!

2024-12-22 21:51 UTC, roman-right commented on beanie/odm/documents.py
> +    def bulk_writer(
Could you please add a test for this method? In case something will be changed later it will prevent breaking changes

2024-12-22 21:51 UTC, roman-right commented on beanie/odm/union_doc.py
> +    def bulk_writer(
Please, add a test for this one as well

2024-12-22 21:51 UTC, roman-right commented on beanie/odm/bulk.py
> +        self.object_class: Optional[Type[Union[Document, UnionDoc]]] = None
I think you can add object class as a constructor parameter here. It should not break any logic but will allow set up the correct class on the very first step

2024-12-24 23:12 UTC, roman-right approved these changes

2024-12-24 23:39 UTC, adeelsohailahmed approved these changes

2024-12-25 23:32 UTC, staticxterm approved these changes

2024-12-25 23:32 UTC, merged