fix #983
BeanieODM/beanie pull request #989
Opened 2024-08-02 18:07 UTC by 07pepa

2024-08-15 13:56 UTC, LawMixer approved these changes

2024-08-15 14:14 UTC, adeelsohailahmed approved these changes

2024-08-17 03:42 UTC, LawMixer approved these changes

2024-08-19 23:32 UTC, Riverfount approved these changes

2024-08-19 23:52 UTC, adeelsohailahmed requested changes
Please update the title of the PR and make it more descriptive.

2024-08-22 07:23 UTC, 07pepa commented
@adeelsohailahmed  done

2024-08-22 18:34 UTC, Riverfount approved these changes

2024-08-22 23:34 UTC, adeelsohailahmed approved these changes
LGTM

2024-08-27 07:15 UTC, merged